name: Publish Package to npmjs
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Publish
    permissions:
      contents: write
      id-token: write
    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v5

      # Step 2: Setup Node.js environment and set npm registry
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm i

      # Step 4: Publish the package to npmjs
      - name: Publish to npmjs
        run: npm publish --access public
